### ISSUE TITLE
Error using haussmeister/suite2p with multiple planes

### ISSUE THREAD

**Issue by pkells12** [neurodroid/haussmeister#4]
Hi! 

I've been able to use haussmeister to load single plane .raw files into suite2p which has sped up my workflow quite a bit! However when I attemt to analyze a fast-z recording taken with ThorImage haussmeister runs into the following error: 

CaiMan import failed
>>>ERROR<<<
stfio module missing
{'data_path': ['/gpfs/gsfs10/users/kellspa/2P_data/in_vitro/011520/slice4/raw_data/Untitled_001'], 'subfolders': [], 'save_path0': '/gpfs/gsfs10/users/kellspa/2P_data/in_vitro/011520/slice4/raw_data/Untitled_001', 'fast_disk': '/gpfs/gsfs10/users/kellspa/2P_data/in_vitro/011520/slice4/raw_data/Untitled_001'}
time %4.2f sec. Using HAUSIO
Reading experiment settings for /gpfs/gsfs10/users/kellspa/2P_data/in_vitro/011520/slice4/raw_data/Untitled_001... The number of planes are: 6
The number of flyback frames are: 2
The number of zplanes is: 8
done
Reading /gpfs/gsfs10/users/kellspa/2P_data/in_vitro/011520/slice4/raw_data/Untitled_001/Image_0001_0001.raw...
===== 2020.01.16 19:01:09 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "/data/kellspa/conda/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/data/kellspa/conda/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "/gpfs/gsfs10/users/kellspa/conda/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 28, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "/gpfs/gsfs10/users/kellspa/conda/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 165, in run_s2p
    ops1 = dataset.tosuite2p(ops)
  File "/data/kellspa/conda/envs/suite2p/lib/python3.7/site-packages/haussmeister-0.2.0-py3.7.egg/haussmeister/haussio.py", line 343, in tosuite2p
    ops1[j]['meanImg'] += im2write.astype(np.float32).sum(axis=0)
KeyError: 'meanImg'
Interrupted by error (not finished)

I could just convert the raw to tiff as I had been doing but I am now unable to use tiff files (is there some sort of way to toggle haussmeister on/off?)

I've tried playing with the inputs in suite2p but nothing seems to work...

Thanks for any help!

**Comment by neurodroid** [comment]
I think that @dkushinsky might have a patch for this issue. It would be good if you could test it to see if it works for you. @dkushinsky would you mind sharing your `haussio.py` file?

**Comment by pkells12** [comment]
Thanks for the quick reply. It looks like @dkushinsky's haussio.py file should work for reading in tiff files after attempting raw but is there a fix for the multiplane issue? I really like the ability to read in raw files. 

Thanks!

**Comment by neurodroid** [comment]
I've added @dkushinsky 's patch. Please test. Apparently there's an issue with the ThorLabs raw file names, which now use a different formats. You may have to set the file name manually in haussio.py.

**Comment by dkushinsky** [comment]
Hi!

I have been using the updated version of haussio.py to effectively read in multi-plane images from thorlabs... please let me know if the uploaded version is working for you, and if not I can send you mine. 

I also noticed that once you have haussmeister installed you can no longer work with tiffs .. to get around this as a sort of hack, I use a conda installed version of suite2p with tiffs (which dosent call haussio.py) and the pip installed version for use with .raw files. 
Note that in the newest haussio.py is assumes the name of the .raw file is Image_001_001.raw instead of Image_0001_0001.raw, as the newest version of ThorImage's default saves files in the shorter way. You can easily change this by editing the .py file.

**Comment by pkells12** [comment]
It works perfectly!

Thank you both so much!
